[changelog]
header = "# Changelog\n\nAll notable changes to YEssential (EndStone Python version) will be documented in this file.\n\n---\n"
footer = ""
sort = "newest"
tag_prefix = "v"
preferred_tag = "semver"

[changelog.sections]
feat = "🎉 新增功能"
fix = "🔧 修复与改进"
perf = "⚡ 性能优化"
refactor = "♻️ 代码重构"
docs = "📝 文档更新"
chore = "🧩 工程维护"

[commit_parsers]
# 匹配fix类提交归到修复改进
{ message = "^fix", section = "fix" }
{ message = "^feat", section = "feat" }